services:
    Theoblin\BonjourBundle\Service\BonjourService: ~

    Theoblin\BonjourBundle\Twig\BonjourExtension:
        arguments:
            $bonjourService: '@Theoblin\BonjourBundle\Service\BonjourService'
        tags:
            - { name: 'twig.extension' }